### ISSUE TITLE
Worker nodes not visible via kubectl get node on VMs with several network interfaces

### ISSUE THREAD

**Issue by Mar4eli** [cookeem/kubeadm-ha#26]
Good day,

First of all, thank you for thorough guide. It helped me a lot!

**Problem description**
OS: CentOS Linux release 7.4.1708 (Core)

I'm using VMs created by vagrant and by default have several network interfaces

```
eth0:  flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.2.15  netmask 255.255.255.0  broadcast 10.0.2.255
        inet6 fe80::5054:ff:fead:3b43  prefixlen 64  scopeid 0x20<link>
        ether 52:54:00:ad:3b:43  txqueuelen 1000  (Ethernet)
        RX packets 141997  bytes 158528777 (151.1 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 40171  bytes 2511712 (2.3 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.120.10  netmask 255.255.255.0  broadcast 192.168.120.255
        inet6 fe80::a00:27ff:fe13:acfa  prefixlen 64  scopeid 0x20<link>
        ether 08:00:27:13:ac:fa  txqueuelen 1000  (Ethernet)
        RX packets 127504  bytes 39089921 (37.2 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 109964  bytes 14854427 (14.1 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

master1 has ip 192.168.120.10
master2 - 192.168.120.82
master3 - 192.168.120.83

Following step

> on devops-master01: use kubeadm to init a kubernetes cluster, notice: you must save the following message: kubeadm join --token XXX --discovery-token-ca-cert-hash YYY , this command will use lately.

I recive join on eth0 network interface.
`kubeadm join --token 7f276c.0741d82a5337f526 10.0.2.15:6443 --discovery-token-ca-cert-hash sha256:c1c15936be9b5c4429cf14074706927a410a150ccb334d6823257cd450f2fe42
`

Adding worker nodes with this line corrupts result of `kubectl get node`. There are only master nodes.

**My solution**
If i edit kubeadm-init.yaml and add advertiseAddress. Everything works fine and `kubectl get node` also return worker nodes.

Kubeadm-init.yaml example:
```
apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
api:
  advertiseAddress: 192.168.120.83
kubernetesVersion: v1.9.1
networking:
  podSubnet: 10.244.0.0/16
  serviceSubnet: 10.96.0.0/12
apiServerCertSANs:
- kuber.master
- kuber.master2
- kuber.master3
- 192.168.120.10
- 192.168.120.82
- 192.168.120.83
- 192.168.120.2
- 127.0.0.1
etcd:
  endpoints:
  - http://192.168.120.10:2379
  - http://192.168.120.82:2379
  - http://192.168.120.83:2379
token: 7f276c.0741d82a5337f526
tokenTTL: "0"
```

**Questions**

1. Am i doing something wrong?
2. Maybe we should add advertiseAddress in guide/your project workflow?

**Comment by cookeem** [comment]
Sorry for reply late, why you use `10.0.2.15:6443` this ip for join? This is your machine ip address not the vm ip address right? I think you should use the vm ip.

```
kubeadm join --token 7f276c.0741d82a5337f526 10.0.2.15:6443 --discovery-token-ca-cert-hash sha256:c1c15936be9b5c4429cf14074706927a410a150ccb334d6823257cd450f2fe42
```

**Comment by Mar4eli** [comment]
I'm not using it, i'm not setting it in create-config.sh, nor putting it anywhere else. It is ip on default network interface eth0 in VM.

When i follow your guide, set VM IP 192.168.120.10 everywhere, kubeadm init cluster with 10.0.2.15:6443. I suppose, iti is becauce eth0 is the default network interface and kubeadm using it if nothing other mentioned. That is why adding advertiseAddress to kubeadm-init.yaml helps.

**Comment by cookeem** [comment]
Yes, you should join the VM network interface eth1 ip not the machine eth0 ip

**Comment by Mar4eli** [comment]
So how about adding advertiseAddress to kubeadm-init.yaml.tpl and using K8SHA_IPLOCAL, something like

```
apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
kubernetesVersion: v1.9.1
api:
  advertiseAddress: K8SHA_IPLOCAL
networking:
  podSubnet: K8SHA_CIDR
  serviceSubnet: K8SHA_SVC_CIDR
...
```
